# 1 Logistik

## 1.1 Allgemeine Informationen
* Leitung: Prof. [Benjamin Stocker](https://geco-group.org/author/benjamin-stocker/); Mitwirkung: Prof. Adrien Mestrot, Prof. Olivia Romppainen-Martius – Geographisches Institut (GIUB), Universität Bern.

* Die Unterrichtssprache ist Deutsch und/oder Englisch.

* Anzahl ECTS: 5 ECTS

* Organisation: Der Kurs findet im Frühjahrssemester 2026 statt. Insgesamt 10 Tage bestehend aus 1-2 Tage Vorbereitung und 8/9 Tage Blockkurs im Juni (08.06.-19.06.2026). Der Blockkurs umfasst eine Reise ins Wallis mit 2 Übernachtungen.

* Maximale Teilnehmendenzahl: 30 Studierende.

* Zielgruppe: Masterstudierende der Geografie 

* Leistungsnachweis: Präsentation (20%), Fragen an Referierende (20%) und Bericht (60%)

## 1.2 Thema und Kontext

Extreme Wetterereignisse erfordern Anpassungen im Management natürlicher Ressourcen, einschließlich Wasserressourcen, Biodiversität, Bodenbewirtschaftung in der Landwirtschaft sowie der Planung einer klimafitten Forstwirtschaft. Informationen sowie kurzfristige Vorhersagen zu Klimaauswirkungen werden durch vielfältige kontinuierliche Messungen und Fernerkundung der Atmosphäre, hydrologischer Systeme, Böden und Ökosysteme gewonnen. In Kombination mit numerischen Wettervorhersagen über einen erweiterten Zeitraum können diese Informationen Planungsprozesse und Maßnahmen auf unterschiedlichen Ebenen unterstützen.

Die kürzlich lancierte Nationale Dürreplattform (https://www.trockenheit.admin.ch) bündelt diese Informationen und stellt sie öffentlich in einer Form bereit, die den unterschiedlichen Anforderungen verschiedener Anspruchsgruppen gerecht wird.

Dieser Feldkurs macht die Studierenden mit einer Vielzahl von Beobachtungssystemen und Messmethoden vertraut, bietet praktische Erfahrungen im Feld und ermöglicht es den Studierenden, die Perspektiven verschiedener Anspruchsgruppen einzunehmen sowie deren Praktiken und Anforderungen kennenzulernen.

## 1.3 Kursaufbau

Der Kurs besteht aus einer Vorbereitungsphase und einer Feldphase. Während der Vorbereitungsphase werden Informationen über den aktuellen Dürrezustand (d.h. in den Wochen vor der Feldphase) unter Berücksichtigung relevanter Erdsystemvariablen erhoben und im Kontext der Klimatologie der letzten 30 Jahre, mittelfristiger (ca. 15 Tage) bis saisonaler Vorhersagen sowie von Klimawandelprojektionen interpretiert.

Die Feldphase umfasst Besuche bei verschiedenen Institutionen, Forschungsstandorten und Orten, die sich mit Dürren, deren Auswirkungen und Anpassungsmaßnahmen befassen. Die Studierenden machen sich mit den unterschiedlichen Perspektiven verschiedener Anspruchsgruppen vertraut und lernen die Prozesse kennen, die Dürrefolgen in unterschiedlichen natürlichen Sphären sowie in sozioökonomischen Bereichen bestimmen.

* Der Kurs wird in 4 Gruppen zu je 5 Studierenden durchgeführt.

* Gruppenaufteilungen:

  Gruppe 1, Wallis: Fragen zu Naters, Pfynwald

  Gruppe 2, Therwil, BL: Fragen zu DokTrial, BAFU, Engehalde

  Gruppe 3, Freiburg: Fragen an den Kanton Freibourg, Swisstopo

  Gruppe 4, Bern: Fragen an die Burgergemeinde, Stadtgrün, MeteoSchweiz, WSL

* Jede Gruppe arbeitet mit mindestens drei verschiedenen Datentypen, z.B.:

  * Niederschlag (MeteoSchweiz-Stationen)
    - Einfache Berechnungen: gleitender Mittelwert über X Tage
    - SPI (Standardized Precipitation Index)
    
  * Abfluss (https://lindas.admin.ch/?lang=en )
  * NDVI (MODIS, Beispielzugang)
  * Bodenfeuchte (ERA5 oder Stationsdaten)
  * Grundwasser (https://www.hydrodaten.admin.ch/)
  * TreeNet (https://treenet.info/)
  
* Der Zugang und das Herunterladen der Daten wird auf der folgenden Seite erklärt und demonstiert (hier dann Link einfügen auf die Data Seite)

Die im Rahmen der Vorbereitungsphase erarbeiteten Datenauswertungen, Visualisierungen, Literaturrecherchen und Fragestellungen bilden die Grundlage für die Präsentationen, die Diskussionen mit den Stakeholdern vor Ort sowie den abschliessenden schriftlichen Bericht.
  
## 1.4 Arbeitsaufträge und Leistungsnachweis

Im Rahmen des Feldkurses übernehmen die Studierenden bereits vor Beginn der Feldphase eigenständige Arbeiten in den Bereichen Datenbeschaffung, Datenanalyse und Datenvisualisierung. Die aufbereiteten Ergebnisse werden am ersten Tag des Blockkurses in einer Gruppenpräsentation vorgestellt.

### Aufgaben vor der Feldphase
Jede Gruppe erarbeitet für ihre Region eine datengestützte Analyse zu Dürrebedingungen und deren Einordnung. Dazu gehören insbesondere:

* Datenbeschaffung für die jeweilige Region
* Datenanalyse und Visualisierung der relevanten Variablen
* Literaturrecherche zur fachlichen Einordnung der Ergebnisse
* Vorbereitung einer Präsentation für den ersten Kurstag
* Vorbereitung von Fragen für die Referierenden und besuchten Institutionen

### Inhalt der Präsentation
Die Präsentation (ca. 30 Minuten) soll folgende Aspekte abdecken:

* Klimatologie der Region, insbesondere:
  * Niederschlag
  * Abfluss
  * Bodenfeuchte
  * Evapotranspiration
* Historische Dürreereignisse
* Aktuelle Messungen und gegenwärtige Bedingungen
* Zukünftige Projektionen (z.B. CH2025)
* Geplante und bereits umgesetzte Massnahmen zur Anpassung an Dürre
* Erkenntnisse aus der Literaturrecherche

Darüber hinaus bereitet jede Gruppe Fragen für die jeweiligen Stakeholder und Referierenden vor. Die Antworten und Erkenntnisse aus den Gesprächen und Besuchen werden im Schlussbericht dokumentiert.

### Leitfragen für Bericht

Der schriftliche Bericht soll sich an folgenden Leitfragen orientieren:

* Was lässt sich aus den Daten über die Dürresituation in der jeweiligen Region lernen?
* Welche Beobachtungen oder Ergebnisse waren besonders überraschend?
* Was wurde aus den Gesprächen mit Referierenden und aus den Exkursionsbesuchen gelernt?
* Wie werden Dürren gemessen und welche Beobachtungen beziehungsweise Datengrundlagen sind dafür notwendig?
* Wie sollte auf zukünftige Veränderungen in Intensität und Häufigkeit von Dürren reagiert werden?
* Welche Anpassungsmassnahmen erscheinen in der jeweiligen Region sinnvoll, realistisch oder bereits wirksam?

### Leistungsnachweis
Die Leistungen im Feldkurs werden wie folgt bewertet:

* Präsentation: 20 %
* Fragen an Referierende / Stakeholder: 20 %
* Schriftlicher Bericht: 60 % 
  
  
  
