# 2 Kursplan

## 2.1 Vorbereitungsphase

### 2.1.1 Nachmittagssession 1 (20.04.2026)

* Kursorganisation, Programm und Lernziele
* Einführung in Sommertrockenheit in der Schweiz und Dürremonitoring
* Identifikation relevanter Schlüsselvariablen
* Einstieg in Datenzugang, -analyse und -interpretation; Einordnung des aktuellen Zustands in einen mehrjährigen Referenzzeitraum
* Vorgehen zur Erhebung von Stakeholder-Perspektiven und Vorbereitung der Exkursionsbesuche

### 2.1.2 Nachmittagssession 2 (11.05.2026)

* Unterstützung beim Datenzugang, bei der Analyse und Interpretation
* Konsolidierung der Fragen an Stakeholder zu einem gemeinsamen Fragenkatalog
* Vorbereitung und Anleitung für Präsentationen (Struktur und Aufbau)

## 2.2 Feldphase

| Datum     | Tag | Morgen                                              | Nachmittag                                     |
|-----------|-----|-----------------------------------------------------|------------------------------------------------|
| 8.6.      | Mo  | Presentation and discussion<br>Weather outlook      | Stadt Bern (Rundgang)                          |
| 9.6.      | Di  | Swisstopo                                           | BAFU                                           |
| 10.6.     | Mi  | DOK Trial Therwil                                   | DOK Trial Therwil                              |
| 11.6.     | Do  | Kanton Freiburg                                     | MeteoSuisse, Payerne                           |
| 12.6.     | Fr  | Drought experiment (Biology, Uni Bern)              | Burgergemeinde Bern                            |
| 14.6.     | So  |                                                     | Travel to Wallis                               |
| 15.6.     | Mo  | Integrales Wasserressourcenmanagement, Naters       | Integrales Wasserressourcenmanagement, Naters<br>Fireside input |
| 16.6.     | Di  | Drought experiment Pfynwald (WSL)                   | Wildfire Leuk<br>Return to Bern                |
